load("//bazel:api_build_system.bzl", "api_go_proto_library", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "gzip",
    srcs = ["gzip.proto"],
    visibility = ["//visibility:public"],
)
