static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8443
  
    filter_chains:
      filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          add_user_agent: true
          idle_timeout: 0.840s
          stat_prefix: egress_http
          
          route_config:
            name: local_route
            virtual_hosts:
            - name: echo-service
              domains:
              - "example.com"
              routes:
              - match:
                  prefix: /
                redirect:
                  https_redirect: true
                  # path_redirect: /

          http_filters:
          - name: envoy.router
            config: {} 
  
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "example.com"
              routes:
              - match:
                  prefix: "/echo"
                route:
                  cluster: echo-service
          http_filters:
          - name: envoy.router
            config: {}

  clusters:
  - name: echo-service
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 10s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: httpbin.org, port_value: 80 }}]
    
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename": "/xfer/DATAWIRE/cert.pem" }
          private_key: { "filename": "/xfer/DATAWIRE/key.pem" }

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
